#!/usr/bin/env bash
# client-setup.sh — Enroll a client machine with Synapse AHA and verify connectivity
#
# Run this on each client machine that needs Storm CLI access to Cortex.
# The admin-enroll-url.txt is generated by deploy.sh and must be shared securely.
#
# Usage:
#   ./client-setup.sh --enroll-url <URL> \
#                     --cortex-host <HOST_IP_OR_FQDN> \
#                     --cortex-port 27495 \
#                     --aha-network synapse \
#                     [--username admin]
#
# Or pass the URL as a positional argument:
#   ./client-setup.sh "ssl://aha.example.com:27272/<guid>?certhash=<sha256>"
#
# After enrollment:
#   - AHA CA certificate is stored in ~/.syn/certs/cas/
#   - User certificate is stored in ~/.syn/certs/users/
#   - Connect to Cortex: python -m synapse.tools.storm "ssl://..."

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────
ENROLL_URL=""
CORTEX_HOST=""
CORTEX_PORT="27495"
AHA_NETWORK="synapse"
USERNAME="admin"
DOMAIN="example.com"

# ─── Argument parsing ────────────────────────────────────────────────────────
# Allow first positional arg as enroll URL
if [[ $# -ge 1 && "$1" != --* ]]; then
  ENROLL_URL="$1"
  shift
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --enroll-url)   ENROLL_URL="$2";   shift 2 ;;
    --cortex-host)  CORTEX_HOST="$2";  shift 2 ;;
    --cortex-port)  CORTEX_PORT="$2";  shift 2 ;;
    --aha-network)  AHA_NETWORK="$2";  shift 2 ;;
    --username)     USERNAME="$2";     shift 2 ;;
    --domain)       DOMAIN="$2";       shift 2 ;;
    --help|-h)
      grep '^#' "$0" | grep -v '#!/' | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

log()  { echo -e "\033[1;34m[client]\033[0m $*"; }
ok()   { echo -e "\033[1;32m[  ok  ]\033[0m $*"; }
warn() { echo -e "\033[1;33m[ warn ]\033[0m $*"; }
die()  { echo -e "\033[1;31m[error ]\033[0m $*" >&2; exit 1; }

# ─── Read enrollment URL from file if not provided ───────────────────────────
if [[ -z "$ENROLL_URL" ]]; then
  ENROLL_FILE="$(dirname "$0")/admin-enroll-url.txt"
  if [[ -f "$ENROLL_FILE" ]]; then
    ENROLL_URL="$(cat "$ENROLL_FILE")"
    log "Read enrollment URL from ${ENROLL_FILE}"
  else
    die "No enrollment URL provided. Pass --enroll-url <URL> or create admin-enroll-url.txt"
  fi
fi

[[ -z "$CORTEX_HOST" ]] && {
  # Try to infer from /etc/hosts
  CORTEX_HOST="$(grep "cortex.${DOMAIN}" /etc/hosts 2>/dev/null | awk '{print $1}' | head -1 || true)"
  [[ -z "$CORTEX_HOST" ]] && die "Could not detect cortex host. Pass --cortex-host <IP_OR_FQDN>"
  log "Inferred Cortex host from /etc/hosts: ${CORTEX_HOST}"
}

# ─── Step 1: Install Synapse if not present ──────────────────────────────────
log "Checking for Synapse installation ..."
if python3 -c "import synapse" &>/dev/null; then
  SYN_VERSION="$(python3 -c "import synapse; print(synapse.version)" 2>/dev/null || echo 'unknown')"
  ok "Synapse already installed (version: ${SYN_VERSION})"
else
  log "Installing Synapse via pip ..."
  python3 -m pip install --upgrade synapse || {
    warn "pip install failed. Trying with --user ..."
    python3 -m pip install --user --upgrade synapse
  }
  ok "Synapse installed"
fi

# ─── Step 2: Verify AHA is reachable ─────────────────────────────────────────
log "Checking AHA reachability ..."
AHA_HOST="$(echo "$ENROLL_URL" | grep -oP '(?<=ssl://)[^:]+' || true)"
AHA_PORT="$(echo "$ENROLL_URL" | grep -oP '(?<=:)\d+(?=/)' | head -1 || echo '27272')"

if [[ -n "$AHA_HOST" ]]; then
  if nc -z -w5 "$AHA_HOST" "$AHA_PORT" 2>/dev/null; then
    ok "AHA reachable at ${AHA_HOST}:${AHA_PORT}"
  else
    warn "Cannot reach AHA at ${AHA_HOST}:${AHA_PORT}"
    warn "Ensure aha.${DOMAIN} resolves to the Docker host IP, or check firewall rules."
    warn "Attempting enrollment anyway ..."
  fi
fi

# ─── Step 3: Enroll with AHA (downloads CA cert + user cert) ─────────────────
log "Enrolling with AHA ..."
log "  URL: ${ENROLL_URL}"
log "  This connects to AHA provisioning port 27272, downloads the CA certificate,"
log "  generates your RSA key pair, and saves your signed user certificate to ~/.syn/"

python3 -m synapse.tools.aha.enroll "${ENROLL_URL}" \
  && ok "Enrollment complete" \
  || die "Enrollment failed. The URL may have already been used (one-time-use only). Ask the admin to generate a new URL with: docker exec <aha-container> python -m synapse.tools.aha.provision.user ${USERNAME}"

# ─── Step 4: Verify certificate files ────────────────────────────────────────
log "Verifying certificate files ..."
SYN_DIR="${HOME}/.syn"
CA_FILE="${SYN_DIR}/certs/cas/${AHA_NETWORK}.crt"
USER_CERT="${SYN_DIR}/certs/users/${USERNAME}@${AHA_NETWORK}.crt"

[[ -f "$CA_FILE" ]]   && ok "CA cert:   ${CA_FILE}"   || warn "CA cert not found at ${CA_FILE}"
[[ -f "$USER_CERT" ]] && ok "User cert: ${USER_CERT}" || warn "User cert not found at ${USER_CERT}"

# ─── Step 5: Update local /etc/hosts if needed ──────────────────────────────
update_hosts() {
  local fqdn="$1"
  local ip="$2"
  if ! grep -qF "${fqdn}" /etc/hosts 2>/dev/null; then
    echo "${ip}  ${fqdn}" | sudo tee -a /etc/hosts >/dev/null
    log "Added /etc/hosts: ${ip}  ${fqdn}"
  fi
}

if ! grep -qF "cortex.${DOMAIN}" /etc/hosts 2>/dev/null; then
  log "Adding *.${DOMAIN} to /etc/hosts (requires sudo) ..."
  update_hosts "aha.${DOMAIN}"      "${CORTEX_HOST}"
  update_hosts "cortex.${DOMAIN}"   "${CORTEX_HOST}"
  update_hosts "axon.${DOMAIN}"     "${CORTEX_HOST}"
  update_hosts "jsonstor.${DOMAIN}" "${CORTEX_HOST}"
  ok "/etc/hosts updated"
fi

# ─── Step 6: Test Storm connection ───────────────────────────────────────────
STORM_URL="ssl://${USERNAME}@${CORTEX_HOST}:${CORTEX_PORT}?hostname=00.cortex.${AHA_NETWORK}&ca=${AHA_NETWORK}"

log "Testing Storm connection to Cortex ..."
log "  URL: ${STORM_URL}"

STORM_TEST_RESULT="$(python3 -m synapse.tools.storm "${STORM_URL}" <<< '$lib.version' 2>&1 || true)"

if echo "$STORM_TEST_RESULT" | grep -qE "^\('" ; then
  SYN_VER="$(echo "$STORM_TEST_RESULT" | grep -oP "\('\K[^']+" | head -1)"
  ok "Storm connection successful! Synapse version: ${SYN_VER}"
elif echo "$STORM_TEST_RESULT" | grep -qi "error\|fail\|refused"; then
  warn "Storm connection test failed. Output:"
  echo "$STORM_TEST_RESULT" | head -20 >&2
  warn "This may be a transient issue. Try the connection manually (see below)."
else
  ok "Storm connection appears successful"
fi

# ─── Step 7: Print connection summary ────────────────────────────────────────
cat << SUMMARY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Client Enrollment Complete
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Username        : ${USERNAME}
  AHA Network     : ${AHA_NETWORK}
  Cortex Host     : ${CORTEX_HOST}
  Cortex Port     : ${CORTEX_PORT}

  Storm CLI:
    python -m synapse.tools.storm \\
      "${STORM_URL}"

  Cortex HTTPS API (browser):
    https://cortex.${DOMAIN}:4443
    (Accept the self-signed cert warning, or replace cert with a CA-signed one)

  See storm-commands.sh for common Storm queries.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUMMARY
